In [1]:
import numpy as np
import pandas as pd

# Data import and generation of the wires_table list.
wire_table = [
    # d_Cu_mm, section_mm2, G1_min, G1_max, G2_min, G2_max, G3_min, G3_max, R20_nom_ohm_m
    (0.036, 0.00101788, 0.040, 0.044, 0.045, 0.049, 0.050, 0.053, 16.79),
    (0.038, 0.00113400, 0.042, 0.046, 0.047, 0.051, 0.052, 0.055, 15.07),
    (0.040, 0.00125700, 0.044, 0.049, 0.050, 0.054, 0.055, 0.058, 13.60),
    (0.043, 0.00145200, 0.047, 0.052, 0.053, 0.058, 0.059, 0.063, 11.770),
    (0.045, 0.00159000, 0.050, 0.055, 0.056, 0.061, 0.062, 0.066, 10.750),
    (0.048, 0.00181000, 0.053, 0.059, 0.060, 0.064, 0.065, 0.069, 9.447),
    (0.050, 0.00196300, 0.055, 0.060, 0.061, 0.066, 0.067, 0.072, 8.706),
    (0.053, 0.00220600, 0.058, 0.064, 0.065, 0.070, 0.071, 0.076, 7.748),
    (0.056, 0.00246300, 0.062, 0.067, 0.068, 0.074, 0.075, 0.081, 6.940),
    (0.060, 0.00282700, 0.066, 0.072, 0.073, 0.079, 0.080, 0.085, 6.046),
    (0.063, 0.00311700, 0.069, 0.076, 0.077, 0.083, 0.084, 0.090, 5.484),
    (0.067, 0.00352600, 0.074, 0.080, 0.081, 0.088, 0.089, 0.095, 4.848),
    (0.070, 0.00384800, 0.077, 0.083, 0.084, 0.090, 0.091, 0.096, 4.442),
    (0.071, 0.00395900, 0.078, 0.084, 0.085, 0.091, 0.092, 0.098, 4.318),
    (0.075, 0.00441800, 0.082, 0.089, 0.090, 0.095, 0.096, 0.102, 3.869),
    (0.080, 0.00502700, 0.087, 0.094, 0.095, 0.101, 0.102, 0.108, 3.401),
    (0.085, 0.00567500, 0.093, 0.100, 0.101, 0.107, 0.108, 0.114, 3.012),
    (0.090, 0.00636200, 0.098, 0.105, 0.106, 0.113, 0.114, 0.120, 2.687),
    (0.095, 0.00708800, 0.103, 0.111, 0.112, 0.119, 0.120, 0.126, 2.412),
    (0.100, 0.00785400, 0.108, 0.117, 0.118, 0.125, 0.126, 0.132, 2.176),
    (0.106, 0.00882500, 0.115, 0.123, 0.124, 0.132, 0.133, 0.140, 1.937),
    (0.110, 0.00950300, 0.119, 0.128, 0.129, 0.137, 0.138, 0.145, 1.799),
    (0.112, 0.00985200, 0.121, 0.130, 0.131, 0.139, 0.140, 0.147, 1.735),
    (0.118, 0.01093600, 0.128, 0.136, 0.137, 0.145, 0.146, 0.154, 1.563),
    (0.120, 0.01131000, 0.130, 0.138, 0.139, 0.148, 0.149, 0.157, 1.511),
    (0.125, 0.01227200, 0.135, 0.144, 0.145, 0.154, 0.155, 0.163, 1.393),
    (0.130, 0.01327300, 0.141, 0.150, 0.151, 0.160, 0.161, 0.169, 1.288),
    (0.132, 0.01368500, 0.143, 0.152, 0.153, 0.162, 0.163, 0.171, 1.249),
    (0.140, 0.01539400, 0.151, 0.160, 0.161, 0.171, 0.172, 0.181, 1.110),
    (0.150, 0.01767100, 0.162, 0.171, 0.172, 0.182, 0.183, 0.193, 0.9673),
    (0.160, 0.02010600, 0.172, 0.182, 0.183, 0.194, 0.195, 0.205, 0.8502),
    (0.170, 0.02269800, 0.183, 0.194, 0.195, 0.205, 0.206, 0.217, 0.7531),
    (0.180, 0.02544700, 0.193, 0.204, 0.205, 0.217, 0.218, 0.229, 0.6718),
    (0.190, 0.02835300, 0.204, 0.216, 0.217, 0.228, 0.229, 0.240, 0.6029),
    (0.200, 0.03141600, 0.214, 0.226, 0.227, 0.239, 0.240, 0.252, 0.5441),
    (0.212, 0.03529900, 0.227, 0.240, 0.241, 0.254, 0.255, 0.268, 0.4843),
    (0.224, 0.03940800, 0.239, 0.252, 0.253, 0.266, 0.267, 0.280, 0.4338),
    (0.236, 0.04374400, 0.253, 0.267, 0.268, 0.283, 0.284, 0.298, 0.3908),
    (0.250, 0.04908700, 0.267, 0.281, 0.282, 0.297, 0.298, 0.312, 0.3482),
    (0.265, 0.05515500, 0.283, 0.297, 0.298, 0.314, 0.315, 0.330, 0.3099),
    (0.280, 0.06157500, 0.298, 0.312, 0.313, 0.329, 0.330, 0.345, 0.2776),
    (0.300, 0.07068600, 0.319, 0.334, 0.335, 0.352, 0.353, 0.369, 0.2418),
    (0.315, 0.07793100, 0.334, 0.349, 0.350, 0.367, 0.368, 0.384, 0.2193),
    (0.335, 0.08814100, 0.355, 0.372, 0.373, 0.391, 0.392, 0.408, 0.1939),
    (0.355, 0.09898000, 0.375, 0.392, 0.393, 0.411, 0.412, 0.428, 0.1727),
    (0.375, 0.11044700, 0.396, 0.414, 0.415, 0.434, 0.435, 0.453, 0.1548),
    (0.400, 0.12566400, 0.421, 0.439, 0.440, 0.459, 0.460, 0.478, 0.1360),
    (0.425, 0.14186300, 0.447, 0.466, 0.467, 0.488, 0.489, 0.508, 0.1205),
    (0.450, 0.15904300, 0.472, 0.491, 0.492, 0.513, 0.514, 0.533, 0.1075),
    (0.475, 0.17720500, 0.499, 0.519, 0.520, 0.541, 0.542, 0.562, 0.09646),
    (0.500, 0.19635000, 0.524, 0.544, 0.545, 0.566, 0.567, 0.587, 0.08706),
]

# Dataframe conversion.
columns = [
    "d_Cu_mm",
    "section_mm2",
    "d_outer_g1_min_mm",
    "d_outer_g1_max_mm",
    "d_outer_g2_min_mm",
    "d_outer_g2_max_mm",
    "d_outer_g3_min_mm",
    "d_outer_g3_max_mm",
    "R20_nom_ohm_m"
]

wires = pd.DataFrame(wire_table, columns=columns)
wires.head()

,d_Cu_mm,section_mm2,d_outer_g1_min_mm,d_outer_g1_max_mm,d_outer_g2_min_mm,d_outer_g2_max_mm,d_outer_g3_min_mm,d_outer_g3_max_mm,R20_nom_ohm_m
0,0.036,0.001018,0.040,0.044,0.045,0.049,0.050,0.053,16.79
1,0.038,0.001134,0.042,0.046,0.047,0.051,0.052,0.055,15.07
2,0.040,0.001257,0.044,0.049,0.050,0.054,0.055,0.058,13.60
3,0.043,0.001452,0.047,0.052,0.053,0.058,0.059,0.063,11.77
4,0.045,0.001590,0.050,0.055,0.056,0.061,0.062,0.066,10.75

In [3]:
# Computation of the outer diameters for each grade (1, 2, 3):
d_outer_g1 = (
    wires["d_outer_g1_min_mm"] + wires["d_outer_g1_max_mm"]
    ) / 2
d_outer_g2 = (
    wires["d_outer_g2_min_mm"] + wires["d_outer_g2_max_mm"]
    ) / 2
d_outer_g3 = (
    wires["d_outer_g3_min_mm"] + wires["d_outer_g3_max_mm"]
    ) / 2

wires["d_outer_g1_mm"] = d_outer_g1
wires["d_outer_g2_mm"] = d_outer_g2
wires["d_outer_g3_mm"] = d_outer_g3

wires.head()

,d_Cu_mm,section_mm2,d_outer_g1_min_mm,d_outer_g1_max_mm,d_outer_g2_min_mm,d_outer_g2_max_mm,d_outer_g3_min_mm,d_outer_g3_max_mm,R20_nom_ohm_m,d_outer_g1_mm,d_outer_g2_mm,d_outer_g3_mm
0,0.036,0.001018,0.040,0.044,0.045,0.049,0.050,0.053,16.79,0.0420,0.0470,0.0515
1,0.038,0.001134,0.042,0.046,0.047,0.051,0.052,0.055,15.07,0.0440,0.0490,0.0535
2,0.040,0.001257,0.044,0.049,0.050,0.054,0.055,0.058,13.60,0.0465,0.0520,0.0565
3,0.043,0.001452,0.047,0.052,0.053,0.058,0.059,0.063,11.77,0.0495,0.0555,0.0610
4,0.045,0.001590,0.050,0.055,0.056,0.061,0.062,0.066,10.75,0.0525,0.0585,0.0640

In [4]:
wires.tail()

,d_Cu_mm,section_mm2,d_outer_g1_min_mm,d_outer_g1_max_mm,d_outer_g2_min_mm,d_outer_g2_max_mm,d_outer_g3_min_mm,d_outer_g3_max_mm,R20_nom_ohm_m,d_outer_g1_mm,d_outer_g2_mm,d_outer_g3_mm
46,0.400,0.125664,0.421,0.439,0.440,0.459,0.460,0.478,0.13600,0.4300,0.4495,0.4690
47,0.425,0.141863,0.447,0.466,0.467,0.488,0.489,0.508,0.12050,0.4565,0.4775,0.4985
48,0.450,0.159043,0.472,0.491,0.492,0.513,0.514,0.533,0.10750,0.4815,0.5025,0.5235
49,0.475,0.177205,0.499,0.519,0.520,0.541,0.542,0.562,0.09646,0.5090,0.5305,0.5520
50,0.500,0.196350,0.524,0.544,0.545,0.566,0.567,0.587,0.08706,0.5340,0.5555,0.5770